apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-indexes
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: disk-indexes-claim
  gcePersistentDisk:
    pdName: disk-indexes-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-indexes-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi