apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-disk
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /adlogs
    server: 10.39.185.98
