apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-core
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: disk-core-claim
  gcePersistentDisk:
    pdName: DISK_NAME
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-core-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
